#pragma once

enum DataPageLayout{
    MAP_AND_2_WIDGETS,
    NO_MAP_AND_5_WIDGETS,
    NO_MAP_AND_6_WIDGETS
};

enum typeData{
    ACTIVITY_TIMER,
    ACTIVITY_HEART_RATE,
    ACTIVITY_CADANCE,
    ACTIVITY_SPEED,
    ACTIVITY_POWER,
    ACTIVITY_REMAINING_KM_ON_ROUTE,
    ACTIVITY_ELAPSED_DISTANCE,
    ACTIVITY_AVG_SPEED,
    ACTIVITY_AVG_CADANCE
};